version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
init:
- ps: >-
    Write-Host APPVEYOR=$env:APPVEYOR

    Write-Host CI=$env:CI

    Write-Host APPVEYOR_API_URL=$env:APPVEYOR_API_URL

    Write-Host APPVEYOR_ACCOUNT_NAME=$env:APPVEYOR_ACCOUNT_NAME

    Write-Host APPVEYOR_PROJECT_ID=$env:APPVEYOR_PROJECT_ID

    Write-Host APPVEYOR_PROJECT_NAME=$env:APPVEYOR_PROJECT_NAME

    Write-Host APPVEYOR_PROJECT_SLUG=$env:APPVEYOR_PROJECT_SLUG

    Write-Host APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER

    Write-Host APPVEYOR_BUILD_ID=$env:APPVEYOR_BUILD_ID

    Write-Host APPVEYOR_BUILD_NUMBER=$env:APPVEYOR_BUILD_NUMBER

    Write-Host APPVEYOR_BUILD_VERSION=$env:APPVEYOR_BUILD_VERSION

    Write-Host APPVEYOR_BUILD_WORKER_IMAGE=$env:APPVEYOR_BUILD_WORKER_IMAGE

    Write-Host APPVEYOR_PULL_REQUEST_NUMBER=$env:APPVEYOR_PULL_REQUEST_NUMBER

    Write-Host APPVEYOR_PULL_REQUEST_TITLE=$env:APPVEYOR_PULL_REQUEST_TITLE

    Write-Host APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME=$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME

    Write-Host APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH=$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH

    Write-Host APPVEYOR_PULL_REQUEST_HEAD_COMMIT=$env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT

    Write-Host APPVEYOR_JOB_ID=$env:APPVEYOR_JOB_ID

    Write-Host APPVEYOR_JOB_NAME=$env:APPVEYOR_JOB_NAME

    Write-Host APPVEYOR_JOB_NUMBER=$env:APPVEYOR_JOB_NUMBER

    Write-Host APPVEYOR_REPO_PROVIDER=$env:APPVEYOR_REPO_PROVIDER

    Write-Host APPVEYOR_REPO_SCM=$env:APPVEYOR_REPO_SCM

    Write-Host APPVEYOR_REPO_NAME=$env:APPVEYOR_REPO_NAME

    Write-Host APPVEYOR_REPO_BRANCH=$env:APPVEYOR_REPO_BRANCH

    Write-Host APPVEYOR_REPO_TAG=$env:APPVEYOR_REPO_TAG

    Write-Host APPVEYOR_REPO_TAG_NAME=$env:APPVEYOR_REPO_TAG_NAME

    Write-Host APPVEYOR_REPO_COMMIT=$env:APPVEYOR_REPO_COMMIT

    Write-Host APPVEYOR_REPO_COMMIT_AUTHOR=$env:APPVEYOR_REPO_COMMIT_AUTHOR

    Write-Host APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL=$env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL

    Write-Host APPVEYOR_REPO_COMMIT_TIMESTAMP=$env:APPVEYOR_REPO_COMMIT_TIMESTAMP

    Write-Host APPVEYOR_REPO_COMMIT_MESSAGE=$env:APPVEYOR_REPO_COMMIT_MESSAGE

    Write-Host APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED=$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED

    Write-Host APPVEYOR_SCHEDULED_BUILD=$env:APPVEYOR_SCHEDULED_BUILD

    Write-Host APPVEYOR_FORCED_BUILD=$env:APPVEYOR_FORCED_BUILD

    Write-Host APPVEYOR_RE_BUILD=$env:APPVEYOR_RE_BUILD

    Write-Host PLATFORM=$env:PLATFORM

    Write-Host CONFIGURATION=$env:CONFIGURATION

    Write-Host APPVEYOR_ARTIFACT_UPLOAD_TIMEOUT=$env:APPVEYOR_ARTIFACT_UPLOAD_TIMEOUT

    Write-Host APPVEYOR_FILE_DOWNLOAD_TIMEOUT=$env:APPVEYOR_FILE_DOWNLOAD_TIMEOUT

    Write-Host APPVEYOR_REPOSITORY_SHALLOW_CLONE_TIMEOUT=$env:APPVEYOR_REPOSITORY_SHALLOW_CLONE_TIMEOUT

    Write-Host APPVEYOR_CACHE_ENTRY_UPLOAD_DOWNLOAD_TIMEOUT=$env:APPVEYOR_CACHE_ENTRY_UPLOAD_DOWNLOAD_TIMEOUT

    Write-Host APPVEYOR_CACHE_SKIP_RESTORE=$env:APPVEYOR_CACHE_SKIP_RESTORE

    Write-Host APPVEYOR_CACHE_SKIP_SAVE=$env:APPVEYOR_CACHE_SKIP_SAVE

    Write-Host APPVEYOR_WAP_ARTIFACT_NAME=$env:APPVEYOR_WAP_ARTIFACT_NAME

    Write-Host APPVEYOR_WAP_SKIP_ACLS=$env:APPVEYOR_WAP_SKIP_ACLS

    Write-Host APPVEYOR_BUILD_WORKER_IMAGE=$env:APPVEYOR_BUILD_WORKER_IMAGE

    Write-Host APPVEYOR_SKIP_FINALIZE_ON_EXIT=$env:APPVEYOR_SKIP_FINALIZE_ON_EXIT

    Write-Host APPVEYOR_SAVE_CACHE_ON_ERROR=$env:APPVEYOR_SAVE_CACHE_ON_ERROR

    Write-Host APPVEYOR_ACS_DEPLOYMENT_UPGRADE_MODE=$env:APPVEYOR_ACS_DEPLOYMENT_UPGRADE_MODE
environment:
  BUILD_CONFIGURATION: Release
  TEST_PROJECT: .\tests\FastWildcard.Tests
  SRC_PROJECT: .\src\FastWildcard
build_script:
- ps: >-
    dotnet build --configuration $env:BUILD_CONFIGURATION


    if (!$env:APPVEYOR_PULL_REQUEST_NUMBER) {
        dotnet pack $env:SRC_PROJECT --configuration $env:BUILD_CONFIGURATION
    }
test_script:
- cmd: dotnet test %TEST_PROJECT% --configuration %BUILD_CONFIGURATION% --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='%APPVEYOR_BUILD_FOLDER%/coverage.xml'
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "$($env:APPVEYOR_BUILD_FOLDER)/coverage.xml"
artifacts:
- path: '**\*.nupkg'
  name: NuGet Package
deploy: off
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Email
  to:
  - alexangas@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true